### ISSUE TITLE
Add a new chat button at the bottom of the chat history window

### ISSUE THREAD

**Issue by King-ning306** [hddevteam/Azure-chatGPT-demo#14]
**Is your feature request related to a problem? Please describe.**
I would like to add a button at the bottom of the chat history window to create a new chat. Currently, there is no convenient way to start a new chat without manually refreshing the page or navigating to a different section.

**Describe the solution you'd like**
I would like to have a button labeled "New Chat" placed at the bottom of the chat history window. When the user clicks on this button, it should create a new chat instance, allowing them to start a fresh conversation.

**Describe alternatives you've considered**
One alternative solution could be adding an icon button next to the input field, but the disadvantage of this approach is that the button is small and not easy for users to notice.

**Additional context**
Attaching a mockup of the button placement and design is provided.

**Comment by hddevteam** [comment]
done
